version: '3.3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build: .
    ports:
      - '8080:8080'
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 5432
    env_file:
      - .env  # configure postgres
    